AWSTemplateFormatVersion: '2010-09-09'
Metadata: 
  License: Apache-2.0
Description: 'AWS CloudFormation Template to create an S3_Website_Bucket_With_Retain_On_Delete'
Parameters:
  MyBucketName:
    Type: String
    Description: Bucket Name
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join ['-', [!Ref MyBucketName, !Ref 'AWS::Region']]
      BucketEncyption: 
        ServerSideEncryptionConfiguration: 
          - ServerSideEncryptionRule
      VersioningConfiguration:
        Status: Enabled
      Tags:
      - Key: "Name"
        Value: "S3-cft"  
    DeletionPolicy: Retain

Outputs:
  S3BucketSecureURL:
    Value: !Join ['', ['https://', !GetAtt [S3Bucket, DomainName]]]
    Description: Name of AWS S3 bucket to hold website content